### ISSUE TITLE
Path to feet vertex IDs

### ISSUE THREAD

**Issue by purvaten** [otaheri/GOAL#2]
Hi Omid,

Thank you for releasing the code and congratulations on the great work!

There are a few places in the code where the path hasn't been updated - e.g., it still points to `/ps/project/`. Specifically, when I run `test/GOAL.py` it looks for the file `feet_verts_ids_0512.npy`. Could you please make this file available?

Thanks in advance!

**Comment by otaheri** [comment]
Thanks for reporting the bugs, they should be fixed now.
