### ISSUE TITLE
TypeError: 'SMPLXLayer' object does not support item assignment

### ISSUE THREAD

**Issue by sypj-98** [otaheri/GOAL#5]
Hi Otaheri,

when trying to train GNet with the following command:
`python train/GNet_train.py --work-dir path/to/work/dir --grab-path /path/to/GRAB --smplx-path /path/to/models/ --expr-id EXPERIMENT_ID
`

I encountered an error below:
`TypeError: 'SMPLXLayer' object does not support item assignment`

There are 4 lines causing such error, which are:
`self.female_model['v_template'] = v_template[females]`  at line 397 in GNet_train.py
`self.male_model['v_template'] = v_template[males]`  at line 423
`self.female_model['v_template'] = v_template[females]`  at line 565 
`self.male_model['v_template'] = v_template[males]`  at line 571

After checking the source code of smplx, I made a substitution and figured out this bug:
`['v_template'] ->  .v_template`

Is it a right correction or there are something else I missed?
Thanks!

**Comment by otaheri** [comment]
Hi @sillybirrrd, thank you for reporting the bug. Yeah, this is the correct way to do it.
