### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yang-master** [otaheri/GOAL#8]
Hello!

I follow the guideline in README.md and successfully run the following command:
`python data/process_gnet_data.py --grab-path /path/to/GRAB --smplx-path /path/to/smplx/models/`
`python data/process_mnet_data.py --grab-path /path/to/GRAB --smplx-path /path/to/smplx/models/`

but when I try to run the following command:
`python test/GOAL.py --work-dir /path/to/work/dir --grab-path /path/to/GRAB --smplx-path /path/to/models/`

I encountered an error below:
`2022-12-19 13:27:51.338 | INFO     | __main__:load_data:152 - Base dataset_dir is /home/ubuntu/yy/GRAB/dataset_unzipped/MNet_data
Traceback (most recent call last):
  File "/home/ubuntu/yy/GOAL/test/GOAL.py", line 699, in <module>
    inference()
  File "/home/ubuntu/yy/GOAL/test/GOAL.py", line 692, in inference
    tester = Trainer(cfg_motion, cfg_static, inference=True)
  File "/home/ubuntu/yy/GOAL/test/GOAL.py", line 88, in __init__
    self.load_data(cfg, inference)
  File "/home/ubuntu/yy/GOAL/test/GOAL.py", line 156, in load_data
    ds_test = LoadData(self.cfg.datasets, split_name=ds_name)
  File "/home/ubuntu/yy/GOAL/./data/mnet_dataloader.py", line 75, in __init__
    [name.split('/')[-2] for name in self.frame_names[:, 10]])
  File "/home/ubuntu/yy/GOAL/./data/mnet_dataloader.py", line 75, in <listcomp>
    [name.split('/')[-2] for name in self.frame_names[:, 10]])
IndexError: list index out of range`

And I can't figure out why it goes wrong. Can you help me find out why?
Thanks!

**Comment by otaheri** [comment]
It seems there could be something wrong with the processed data. Are you using the correct path to the unzipped GRAB data when running the process_*_data code? 

Also, can you check what is the shape of the ```self.frame_names```? it should be ```n*21*, if not, please check if you processed the data correctly.

Hope this helps.
